@startuml
class PrintingSystemContext {
    + PrintingSystemContext()
    + PrintingSystemContext(options:DbContextOptions<PrintingSystemContext>)
    # <<override>> OnConfiguring(optionsBuilder:DbContextOptionsBuilder) : void
    # <<override>> OnModelCreating(modelBuilder:ModelBuilder) : void
}
class "DbSet`1"<T> {
}
DbContext <|-- PrintingSystemContext
PrintingSystemContext --> "Users<User>" "DbSet`1"
PrintingSystemContext --> "Products<Product>" "DbSet`1"
PrintingSystemContext --> "Cards<Card>" "DbSet`1"
PrintingSystemContext --> "Transactions<Transaction>" "DbSet`1"
@enduml
