@startuml
class PrintsystemServices {
    - <<readonly>> _baseUrl : string = "https://localhost:7101"
    + PrintsystemServices(client:HttpClient)
    + <<async>> AuthenticateByUsername(userAuth:AuthentificationM) : Task<AuthentificationM>
    + <<async>> creditUsernameWithQuotaCHF(user:UserM) : Task<UserM>
}
IPrintsystemServices <|-- PrintsystemServices
PrintsystemServices --> "_client" HttpClient
@enduml
