@startuml
class BalanceService {
    - <<readonly>> _baseUrl : string = "https://localhost:7101"
    + BalanceService(client:HttpClient)
    + <<async>> CreditUserWithQuotaCHFAsync(userId:Guid, quotaCHF:decimal) : Task<UserM>
    + <<async>> GetUserBalanceAsync(userId:Guid) : Task<UserM>
}
IBalanceService <|-- BalanceService
BalanceService --> "_client" HttpClient
@enduml
