@startuml
class Transaction {
    - Transaction()
    + Transaction(userId:Guid, pageCount:int, product:Product)
    + PageCount : int <<get>> <<set>>
    + TotalCopyQuotaInTransaction : int <<get>> <<set>>
    + TotalCHFInTransaction : decimal <<get>> <<set>>
    + TotalQuotaCHFInTransaction : decimal <<get>> <<set>>
    + ApplyToUserBalance() : void
}
Transaction --> "TransactionID" Guid
Transaction --> "Date" DateTime
Transaction --> "UserID" Guid
Transaction --> "User" User
Transaction --> "ProductID" Guid
Transaction --> "Product" Product
@enduml
