@startuml
class User {
    # User()
    + User(firstName:string, lastName:string, password:string, username:string, group:string)
    + Username : string <<get>> <<set>>
    + FirstName : string <<get>> <<set>>
    + LastName : string <<get>> <<set>>
    + Password : string <<get>> <<set>>
    + Group : string <<get>> <<set>>
    + IsActive : bool <<get>> <<set>>
    + CopyQuota : int <<get>> <<set>>
    + CHF : decimal <<get>> <<set>>
    + QuotaCHF : decimal <<get>> <<set>>
}
class "ICollection`1"<T> {
}
User --> "UserID" Guid
User --> "CreationDate" DateTime
User --> "Card" Card
User --> "Transactions<Transaction>" "ICollection`1"
@enduml
