@startuml
class BalanceHelper {
    + BalanceHelper(repo:PrintingSystemContext, authHelper:IAuthentificationHelper)
    + additionQuotaCHF(quotaCHF:decimal, actualQuotaCHF:decimal) : decimal
    + convertQuotaCHFToCopyQuota(quotaCHF:decimal) : int
    + <<async>> getQuotaCHFByUID(userID:Guid) : Task<decimal>
    + <<async>> updateCopyQuotaByUID(userID:Guid, copyQuota:int) : Task<int>
    + <<async>> updateQuotaCHFByUID(userID:Guid, quotaCHF:decimal) : Task<decimal>
    + <<async>> creditUIDWithQuotaCHF(userID:Guid, quotaCHF:decimal) : Task<(decimal , int, bool )>
    + <<async>> creditUsernameWithQuotaCHF(username:string, quotaCHF:decimal) : Task<(decimal ,bool )>
}
IBalanceHelper <|-- BalanceHelper
BalanceHelper --> "_repo" PrintingSystemContext
BalanceHelper --> "_authHelper" IAuthentificationHelper
@enduml
