@startuml
interface IAuthentificationHelper {
    authenticateByCard(cardId:Guid) : Task<(string, Guid?)>
    authenticateByUsername(username:string, password:string) : Task<(string, Guid?)>
    checkUsername(username:string) : Task<bool>
    authenticateByUsernameWithStaffCheck(username:string, password:string) : Task<(string message, Guid? uid, bool isStaff, string group)>
    cardIDExists(cardID:Guid) : Task<bool>
    isCardActive(cardID:Guid) : Task<bool>
    getUIDByCardID(cardID:Guid) : Task<Guid>
    getUIDByUsername(username:string) : Task<Guid>
    usernameExists(username:string) : Task<bool>
    verifyPasswordWithUsername(username:string, password:string) : Task<bool>
    isUserStaff(userId:Guid) : Task<bool>
}
@enduml
