@startuml
class BalanceController {
    + BalanceController(balanceService:IBalanceService)
    + CreditUser(userId:Guid) : IActionResult
    + <<async>> CreditUser(model:BalanceM) : Task<IActionResult>
    + <<async>> UserBalance(userId:Guid) : Task<IActionResult>
}
Controller <|-- BalanceController
BalanceController --> "_balanceService" IBalanceService
@enduml
