@startuml
class AuthenticationController {
    + AuthenticationController(authentificationHelper:IAuthentificationHelper)
    + <<async>> checkUsername(username:string) : Task<ActionResult<Guid>>
    + <<async>> AuthenticateByCard(request:CardAuthenticationRequestDTO) : Task<ActionResult>
    + <<async>> AuthenticateByUsername(request:AuthenticationRequestDTO) : Task<ActionResult>
}
ControllerBase <|-- AuthenticationController
AuthenticationController --> "_authentificationHelper" IAuthentificationHelper
@enduml
