@startuml
class BalanceController {
    + BalanceController(balanceHelper:IBalanceHelper)
    + <<async>> CreditUIDWithQuotaCHF(request:CreditUIDRequestDTO) : Task<ActionResult<(decimal, int, bool)>>
    + <<async>> CreditUsernameWithQuotaCHF(request:CreditUsernameRequestDTO) : Task<ActionResult<(decimal, bool)>>
    + <<async>> CreditGroupWithQuotaCHF(request:CreditGroupRequestDTO) : Task<ActionResult<(List<User>, decimal, bool)>>
}
ControllerBase <|-- BalanceController
BalanceController --> "_balanceHelper" IBalanceHelper
@enduml
