@startuml
class DiagramGenerator {
    + DiagramGenerator()
    + <<async>> GenerateDiagramAsync(plantUmlText:string, outputPath:string) : Task
}
DiagramGenerator --> "_renderer" IPlantUmlRenderer
@enduml
